#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

console.log('🔧 Preparing build environment...\n');

const dirs = [
  'src/main',
  'src/renderer',
  'resources/icons',
  'config',
  'build',
  'dist'
];

dirs.forEach(dir => {
  const fullPath = path.join(process.cwd(), dir);
  if (!fs.existsSync(fullPath)) {
    fs.mkdirSync(fullPath, { recursive: true });
    console.log(`   ✓ Created: ${dir}`);
  }
});

const files = {
  'LICENSE': 'MIT License\n\nCopyright (c) 2024 CleanGenius AI\n\nPermission is hereby granted, free of charge, to any person obtaining a copy...',
  'README.md': '# CleanGenius AI\n\nAI-powered Windows disk cleanup utility.',
  'build/installer.nsh': '!macro customInstall\n  DetailPrint "Configuring CleanGenius AI..."\n!macroend\n'
};

Object.entries(files).forEach(([file, content]) => {
  const fullPath = path.join(process.cwd(), file);
  if (!fs.existsSync(fullPath)) {
    fs.writeFileSync(fullPath, content);
    console.log(`   ✓ Created: ${file}`);
  }
});

// Create valid PNG icon if missing
const iconDir = path.join(process.cwd(), 'resources/icons');
const iconPngPath = path.join(iconDir, 'icon.png');

if (!fs.existsSync(iconPngPath)) {
  const pngData = Buffer.from(
    'iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAARUSURBVHja7doxAQAgEMCwf+l3RwghBjR0PDMZQO37BQD/CwBAAIAAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAARAAABAAEBAgAAAAQEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAAEBAQABAAEBAQABAAEBAQABAAEBAQABAYEBAQABg08BKaUL/Wk1gzEAAAAASUVORK5CYII=',
    'base64'
  );
  fs.writeFileSync(iconPngPath, pngData);
  console.log('   ✓ Created icon.png');
}

console.log('\n✅ Build preparation complete!\n');
