"""
CleanGenius AI - Local Rules Engine
Deterministic, 100% offline rule-based cleanup and safety scoring.
"""

import os
from typing import Dict, List, Any

CATEGORY_SAFETY_SCORES = {
    "temp_files": 10,
    "browser_cache": 9,
    "dev_cache": 9,
    "log_files": 8,
    "registry_junk": 8,
    "installers": 6,
    "miscellaneous": 5,
    "system_protected": 1
}

CATEGORY_REASONING = {
    "temp_files": "Temporary operating system and application files that can be safely removed without affecting functionality.",
    "browser_cache": "Cached web pages, images, and scripts. Deleting them frees disk space and resets web storage.",
    "dev_cache": "Build artifacts (e.g. node_modules, __pycache__, target, dist) that can be easily regenerated by build tools.",
    "log_files": "Historical log files generated by application activity. Safe to delete for disk maintenance.",
    "registry_junk": "Orphaned registry entries, invalid MRU paths, or uninstaller leftovers.",
    "installers": "Downloaded setup packages (.msi, .iso, .exe) that may no longer be required after installation.",
    "miscellaneous": "Uncategorized large or old files requiring manual user review.",
    "system_protected": "Critical system files or protected operating system components. Do NOT delete."
}

class RulesEngine:
    """
    Local Rules Engine providing offline file analysis, category safety scores,
    and recommended cleanup actions without requiring external AI APIs.
    """

    def analyze(self, scan_results: Dict[str, Any]) -> Dict[str, Any]:
        categories = scan_results.get("categories", {})
        files = scan_results.get("files", [])

        recommendations = []
        total_safe_deletable_bytes = 0
        total_risky_bytes = 0
        recommended_order = []

        # Sort categories by safety score descending
        sorted_cats = sorted(
            categories.items(),
            key=lambda item: CATEGORY_SAFETY_SCORES.get(item[0], 5),
            reverse=True
        )

        for cat, data in sorted_cats:
            score = CATEGORY_SAFETY_SCORES.get(cat, 5)
            size_bytes = data.get("size_bytes", 0) if isinstance(data, dict) else 0
            size_gb = size_bytes / (1024 ** 3)

            if score >= 8:
                action = "delete"
                total_safe_deletable_bytes += size_bytes
            elif score >= 5:
                action = "review"
                total_risky_bytes += size_bytes
            else:
                action = "keep"
                total_risky_bytes += size_bytes

            recommended_order.append(cat)

            recommendations.append({
                "category": cat,
                "action": action,
                "safety_score": score,
                "space_savings_gb": round(size_gb, 3),
                "reasoning": CATEGORY_REASONING.get(cat, f"Local rule-based recommendation for {cat}."),
                "conditions": [
                    f"Safety Score: {score}/10",
                    "Deterministic local rule evaluation",
                    "Recycle Bin recovery point created before cleanup"
                ]
            })

        safe_gb = total_safe_deletable_bytes / (1024 ** 3)
        risky_gb = total_risky_bytes / (1024 ** 3)

        return {
            "engine": "local_rules",
            "ai_enhanced": False,
            "recommendations": recommendations,
            "overall_assessment": {
                "safe_to_delete_gb": round(safe_gb, 3),
                "risky_deletion_gb": round(risky_gb, 3),
                "recommended_order": recommended_order
            },
            "warnings": [
                "System protected paths (C:\\Windows\\System32, WinSxS) are automatically excluded.",
                "Rollback recovery points are enabled for all cleanup operations."
            ]
        }
